name: Build for Release

on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Version (Tag Name (Do not include the build number))'
        required: true

env:
  FLUTTER_VERSION: '3.41.6'

run-name: Build release version ${{ inputs.TAG_NAME }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: sudo apt-get install -y jq

      - name: Install yq
        run: pip install yq

      - name: Check tag with project version
        run: |
          TAG_NAME=${{ github.event.inputs.TAG_NAME }}
          PROJECT_VERSION=$(sed 's/\+.*$//g' <<< $(yq .version pubspec.yaml --raw-output))
          # Remove 'v' prefix from tag name
          TAG_VERSION=$(sed 's/^v//g' <<< "$TAG_NAME")
          if [ "$PROJECT_VERSION" != "$TAG_VERSION" ]; then
              echo "::error title=Mismatched Versions!::Project version ($PROJECT_VERSION) does not match tag ($TAG_VERSION)"
              exit 1
          fi

  build:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Get dependencies
        run: flutter pub get

      - name: Generate launcher icons
        run: dart run flutter_launcher_icons

      - name: Build Universal
        run: flutter build apk --release

      - name: Build Per ABI
        run: flutter build apk --release --split-per-abi

      - name: Prepare for upload
        run: |
          mkdir upload
          mv ./build/app/outputs/flutter-apk/app-release.apk ./upload/SimpleAudioConverter_${{ github.event.inputs.TAG_NAME }}-universal.apk
          mv ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ./upload/SimpleAudioConverter_${{ github.event.inputs.TAG_NAME }}-arm64-v8a.apk
          mv ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk ./upload/SimpleAudioConverter_${{ github.event.inputs.TAG_NAME }}-armeabi-v7a.apk
          mv ./build/app/outputs/flutter-apk/app-x86_64-release.apk ./upload/SimpleAudioConverter_${{ github.event.inputs.TAG_NAME }}-x86_64.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: SimpleAudioConverter_${{ github.event.inputs.TAG_NAME }}
          path: ./upload/*.apk
